// React/src/App.tsx
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import CardView, {
  Column,
  ColumnChooser,
  HeaderFilter,
  Pager,
  Paging,
  Position,
  SearchPanel,
  Selection,
} from 'devextreme-react/card-view';
import { employees } from './data';

function App(): JSX.Element {
  return (
    <CardView
      dataSource={employees}
      width={1000}
      keyExpr="ID"
      allowColumnReordering={true}
      cardsPerRow="auto"
      cardMinWidth={200}
    >
      <Paging
        pageSize={3}
      />
      <Pager
        showInfo={true}
        showNavigationButtons={true}
        showPageSizeSelector={true}
      />
      <Selection mode="multiple" />
      <HeaderFilter visible={true} />
      <SearchPanel visible={true} />
      <ColumnChooser
        enabled={true}
        height={340}
        mode="select"
      >
        <Position
          my="right top"
          at="right bottom"
          of=".dx-cardview-column-chooser-button"
        />
        <Selection selectByClick={true} />
      </ColumnChooser>
      <Column dataField="FullName" allowHiding={false} />
      <Column dataField="Position" />
      <Column dataField="Email" />
    </CardView>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Employee, Service } from './app.service';
import { DxCardViewTypes } from 'devextreme-angular/card-view';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [Service],
})
export class AppComponent {
  title = 'Angular';

  employees: Employee[];

  constructor(service: Service) {
    this.employees = service.getEmployees();
  }

  getColumnChooserConfig(): DxCardViewTypes.ColumnChooser {
    return {
      enabled: true,
      height: 340,
      mode: 'select',
      position: {
        my: 'right top',
        at: 'right bottom',
        of: '.dx-cardview-column-chooser-button',
      },
      selection: {
        selectByClick: true,
      },
    };
  }
}

<dx-card-view
  [dataSource]="employees"
  [width]="1000"
  keyExpr="ID"
  [allowColumnReordering]="true"
  cardsPerRow="auto"
  [cardMinWidth]="200"
>
  <dxo-card-view-paging [pageSize]="3"></dxo-card-view-paging>
  <dxo-card-view-pager
    [showInfo]="true"
    [showNavigationButtons]="true"
    [showPageSizeSelector]="true"
  ></dxo-card-view-pager>
  <dxo-card-view-selection mode="multiple"></dxo-card-view-selection>
  <dxo-card-view-header-filter [visible]="true"></dxo-card-view-header-filter>
  <dxo-card-view-search-panel [visible]="true"></dxo-card-view-search-panel>
  <dxo-card-view-column-chooser [enabled]="true" [height]="340" mode="select">
    <dxo-card-view-column-chooser-selection
      [selectByClick]="true"
    ></dxo-card-view-column-chooser-selection>
    <dxo-card-view-column-chooser-position
      my="right top"
      at="right bottom"
      of=".dx-cardview-column-chooser-button"
    ></dxo-card-view-column-chooser-position>
  </dxo-card-view-column-chooser>
  <dxi-card-view-column
    dataField="FullName"
    [allowHiding]="false"
  ></dxi-card-view-column>
  <dxi-card-view-column
    dataField="Position"
  ></dxi-card-view-column>
  <dxi-card-view-column
    dataField="Email"
  ></dxi-card-view-column>
</dx-card-view>
